dist: xenial
sudo: required
language: cpp

cache:
    directories:
        - $HOME/prereq
        - $HOME/local

jobs:
    include:
        - name: "Build"
          script:
            - bash ci/install-packages.sh
            - bash ci/setup-prereq-ext.sh
            - bash ci/setup-prereq.sh
            - bash ci/setup-credb.sh
            - bash env run_test=unit_test -e downstream=0 credb ../ci/run-test.sh
  
