dist: xenial
sudo: required
language: cpp

cache:
    directories:
        - $HOME/prereq
        - $HOME/local

jobs:
    include:
        - name: "Build"
          script:
            - bash ci/install-packages.sh
            - bash ci/setup-prereq-ext.sh
            - bash ci/setup-prereq.sh
            - bash ci/setup-credb.sh

        - name: "Test"
          script:
            - bash ci/install-packages.sh
            - env run_test=multi_get ci/run-test.sh
            - env run_test=multi_update ci/run-test.sh
